spring.application.name=BNPL

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:aplazo}
spring.datasource.username=${POSTGRES_USER:aplazo}
spring.datasource.password=${POSTGRES_PASSWORD:aplazo1234}
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=EVWAi8hrgdFzt5XMwn5D7dFiGa7qQbEtinKveTGiNLnG0wXQSTaccJ3EW9iaQnpkA63ev7LMCVfL
jwt.expiration=3600000