spring.application.name=BNPL

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:aplazo}
spring.datasource.username=${POSTGRES_USER:aplazo}
spring.datasource.password=${POSTGRES_PASSWORD:aplazo1234}
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=&)X0&6!y}gQ?hzTVX81WVhu5F%ff[7aHGWQMd,Kk1m5,fz/mZ6q74Sc9%S=)$EnXSxV=RXZ&.uB
jwt.expiration=3600000